// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package storagedi

import (
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/hifat/kubo-storage-api/config"
	"github.com/hifat/kubo-storage-api/internal/storage/handler"
	"github.com/hifat/kubo-storage-api/internal/storage/repository"
	"github.com/hifat/kubo-storage-api/internal/storage/service"
	"github.com/hifat/kubo-storage-api/pkg/logger"
)

// Injectors from wire.go:

func Init(cfg *config.Config, log logger.Logger, client *s3.Client, presignClient *s3.PresignClient) *storagehdl.Handler {
	repository := storagerepo.NewR2(cfg, client, presignClient)
	service := storagesvc.New(log, repository)
	grpc := storagehdl.NewGRPC(service)
	handler := storagehdl.New(grpc)
	return handler
}
