// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package middlewaredi

import (
	"github.com/hifat/kubo-storage-api/config"
	"github.com/hifat/kubo-storage-api/internal/middleware/handler"
	"github.com/hifat/kubo-storage-api/internal/middleware/service"
	"github.com/hifat/kubo-storage-api/pkg/logger"
)

// Injectors from wire.go:

func Init(cfg *config.Config, log logger.Logger) *middlewarehdl.Handler {
	service := middlewaresvc.New(cfg, log)
	grpc := middlewarehdl.NewGRPC(service)
	handler := middlewarehdl.New(grpc)
	return handler
}
